<?php
php_sapi_name();
    
    // Requested file
    // Could also be e.g. 'currencies.json' or 'historical/2011-01-01.json'
    $file = 'latest.json';
    $appId = 'af94a138eabd4539b6eddf79cf965254';
    
    // Open CURL session:
    $ch = curl_init("http://openexchangerates.org/api/{$file}?app_id={$appId}");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    
    // Get the data:
    $json = curl_exec($ch);
    curl_close($ch);
    
    // Decode JSON response:
    $exchangeRates = json_decode($json);

    //echo'<pre>';
    //print_r($exchangeRates);
    //echo'</pre>';

     //$base = $exchangeRates->base;
     error_reporting(E_ERROR | E_PARSE);
     $base = $exchangeRates->base;
     $date = date('H:i jS F, Y', $exchangeRates->timestamp);
        $AED = $exchangeRates->rates->AED;
        $AFN = $exchangeRates->rates->AFN;
        $ALL = $exchangeRates->rates->ALL;
        $AMD = $exchangeRates->rates->AMD;
        $ANG = $exchangeRates->rates->ANG;
        $AOA = $exchangeRates->rates->AOA;
        $ARS = $exchangeRates->rates->ARS;
        $AUD = $exchangeRates->rates->AUD;
        $AWG = $exchangeRates->rates->AWG;
        $AZN = $exchangeRates->rates->AZN;
        $BAM = $exchangeRates->rates->BAM;
        $BBD = $exchangeRates->rates->BBD;
        $BDT = $exchangeRates->rates->BDT;
        $BGN = $exchangeRates->rates->BGN;
        $BHD = $exchangeRates->rates->BHD;
        $BIF = $exchangeRates->rates->BIF;
        $BMD = $exchangeRates->rates->BMD;
        $BND = $exchangeRates->rates->BND;
        $BOB = $exchangeRates->rates->BOB;
        $BRL = $exchangeRates->rates->BRL;
        $BSD = $exchangeRates->rates->BSD;
        $BTC = $exchangeRates->rates->BTC;
        $BTN = $exchangeRates->rates->BTN;
        $BWP = $exchangeRates->rates->BWP;
        $BYR = $exchangeRates->rates->BYR;
        $BZD = $exchangeRates->rates->BZD;
        $CAD = $exchangeRates->rates->CAD;
        $CDF = $exchangeRates->rates->CDF;
        $CHF = $exchangeRates->rates->CHF;
        $CLF = $exchangeRates->rates->CLF;
        $CLP = $exchangeRates->rates->CLP;
        $CNY = $exchangeRates->rates->CNY;
        $COP = $exchangeRates->rates->COP;
        $CRC = $exchangeRates->rates->CRC;
        $CUP = $exchangeRates->rates->CUP;
        $CVE = $exchangeRates->rates->CVE;
        $CZK = $exchangeRates->rates->CZK;
        $DJF = $exchangeRates->rates->DJF;
        $DKK = $exchangeRates->rates->DKK;
        $DOP = $exchangeRates->rates->DOP;
        $DZD = $exchangeRates->rates->DZD;
        $EEK = $exchangeRates->rates->EEK;
        $EGP = $exchangeRates->rates->EGP;
        $ERN = $exchangeRates->rates->ERN;
        $ETB = $exchangeRates->rates->ETB;
        $EUR = $exchangeRates->rates->EUR;
        $FJD = $exchangeRates->rates->FJD;
        $FKP = $exchangeRates->rates->FKP;
        $GBP = $exchangeRates->rates->GBP;
        $GEL = $exchangeRates->rates->GEL;
        $GGP = $exchangeRates->rates->GGP;
        $GHS = $exchangeRates->rates->GHS;
        $GIP = $exchangeRates->rates->GIP;
        $GMD = $exchangeRates->rates->GMD;
        $GNF = $exchangeRates->rates->GNF;
        $GTQ = $exchangeRates->rates->GTQ;
        $GYD = $exchangeRates->rates->GYD;
        $HKD = $exchangeRates->rates->HKD;
        $HNL = $exchangeRates->rates->HNL;
        $HRK = $exchangeRates->rates->HRK;
        $HTG = $exchangeRates->rates->HTG;
        $HUF = $exchangeRates->rates->HUF;
        $IDR = $exchangeRates->rates->IDR;
        $ILS = $exchangeRates->rates->ILS;
        $IMP = $exchangeRates->rates->IMP;
        $INR = $exchangeRates->rates->INR;
        $IQD = $exchangeRates->rates->IQD;
        $IRR = $exchangeRates->rates->IRR;
        $ISK = $exchangeRates->rates->ISK;
        $JEP = $exchangeRates->rates->JEP;
        $JMD = $exchangeRates->rates->JMD;
        $JOD = $exchangeRates->rates->JOD;
        $JPY = $exchangeRates->rates->JPY;
        $KES = $exchangeRates->rates->KES;
        $KGS = $exchangeRates->rates->KGS;
        $KHR = $exchangeRates->rates->KHR;
        $KMF = $exchangeRates->rates->KMF;
        $KPW = $exchangeRates->rates->KPW;
        $KRW = $exchangeRates->rates->KRW;
        $KWD = $exchangeRates->rates->KWD;
        $KYD = $exchangeRates->rates->KYD;
        $KZT = $exchangeRates->rates->KZT;
        $LAK = $exchangeRates->rates->LAK;
        $LBP = $exchangeRates->rates->LBP;
        $LKR = $exchangeRates->rates->LKR;
        $LRD = $exchangeRates->rates->LRD;
        $LSL = $exchangeRates->rates->LSL;
        $LTL = $exchangeRates->rates->LTL;
        $LVL = $exchangeRates->rates->LVL;
        $LYD = $exchangeRates->rates->LYD;
        $MAD = $exchangeRates->rates->MAD;
        $MDL = $exchangeRates->rates->MDL;
        $MGA = $exchangeRates->rates->MGA;
        $MKD = $exchangeRates->rates->MKD;
        $MMK = $exchangeRates->rates->MMK;
        $MNT = $exchangeRates->rates->MNT;
        $MOP = $exchangeRates->rates->MOP;
        $MRO = $exchangeRates->rates->MRO;
        $MTL = $exchangeRates->rates->MTL;
        $MUR = $exchangeRates->rates->MUR;
        $MVR = $exchangeRates->rates->MVR;
        $MWK = $exchangeRates->rates->MWK;
        $MXN = $exchangeRates->rates->MXN;
        $MYR = $exchangeRates->rates->MYR;
        $MZN = $exchangeRates->rates->MZN;
        $NAD = $exchangeRates->rates->NAD;
        $NGN = $exchangeRates->rates->NGN;
        $NIO = $exchangeRates->rates->NIO;
        $NOK = $exchangeRates->rates->NOK;
        $NPR = $exchangeRates->rates->NPR;
        $NZD = $exchangeRates->rates->NZD;
        $OMR = $exchangeRates->rates->OMR;
        $PAB = $exchangeRates->rates->PAB;
        $PEN = $exchangeRates->rates->PEN;
        $PGK = $exchangeRates->rates->PGK;
        $PHP = $exchangeRates->rates->PHP;
        $PKR = $exchangeRates->rates->PKR;
        $PLN = $exchangeRates->rates->PLN;
        $PYG = $exchangeRates->rates->PYG;
        $QAR = $exchangeRates->rates->QAR;
        $RON = $exchangeRates->rates->RON;
        $RSD = $exchangeRates->rates->RSD;
        $RUB = $exchangeRates->rates->RUB;
        $RWF = $exchangeRates->rates->RWF;
        $SAR = $exchangeRates->rates->SAR;
        $SBD = $exchangeRates->rates->SBD;
        $SCR = $exchangeRates->rates->SCR;
        $SDG = $exchangeRates->rates->SDG;
        $SEK = $exchangeRates->rates->SEK;
        $SGD = $exchangeRates->rates->SGD;
        $SHP = $exchangeRates->rates->SHP;
        $SLL = $exchangeRates->rates->SLL;
        $SOS = $exchangeRates->rates->SOS;
        $SRD = $exchangeRates->rates->SRD;
        $STD = $exchangeRates->rates->STD;
        $SVC = $exchangeRates->rates->SVC;
        $SYP = $exchangeRates->rates->SYP;
        $SZL = $exchangeRates->rates->SZL;
        $THB = $exchangeRates->rates->THB;
        $TJS = $exchangeRates->rates->TJS;
        $TMT = $exchangeRates->rates->TMT;
        $TND = $exchangeRates->rates->TND;
        $TOP = $exchangeRates->rates->TOP;
        $TRY = $exchangeRates->rates->TRY;
        $TTD = $exchangeRates->rates->TTD;
        $TWD = $exchangeRates->rates->TWD;
        $TZS = $exchangeRates->rates->TZS;
        $UAH = $exchangeRates->rates->UAH;
        $UGX = $exchangeRates->rates->UGX;
        $USD = $exchangeRates->rates->USD;
        $UYU = $exchangeRates->rates->UYU;
        $UZS = $exchangeRates->rates->UZS;
        $VEF = $exchangeRates->rates->VEF;
        $VND = $exchangeRates->rates->VND;
        $VUV = $exchangeRates->rates->VUV;
        $WST = $exchangeRates->rates->WST;
        $XAF = $exchangeRates->rates->XAF;
        $XAG = $exchangeRates->rates->XAG;
        $XAU = $exchangeRates->rates->XAU;
        $XCD = $exchangeRates->rates->XCD;
        $XDR = $exchangeRates->rates->XDR;
        $XOF = $exchangeRates->rates->XOF;
        $XPF = $exchangeRates->rates->XPF;
        $YER = $exchangeRates->rates->YER;
        $ZAR = $exchangeRates->rates->ZAR;
        $ZMK = $exchangeRates->rates->ZMK;
        $ZMW = $exchangeRates->rates->ZMW;
        $ZWL = $exchangeRates->rates->ZWL;
     

echo "
    <tr><td>$base</td><td>$PHP</td><td>$KRW</td><td>$CNY</td><td>$JPY</td><td>$CAD</td><td>$USD</td><td>$GBP</td><td>$EUR</td><td>$AED</td></tr>
";

?>